// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtgJQCqGYXm10epb5cUcLBuc4528YcYNE',
    appId: '1:80742676487:web:3c725a953b4293803192a2',
    messagingSenderId: '80742676487',
    projectId: 'focus-to-do-8e9e4',
    authDomain: 'focus-to-do-8e9e4.firebaseapp.com',
    storageBucket: 'focus-to-do-8e9e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgreFDxGNja2-6Xtlvu18qF72vceDxeg',
    appId: '1:80742676487:android:7f33858040e507113192a2',
    messagingSenderId: '80742676487',
    projectId: 'focus-to-do-8e9e4',
    storageBucket: 'focus-to-do-8e9e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFuleDPDNLoXWKrLxQweIrJwEVLzDg4I',
    appId: '1:80742676487:ios:1afc9a05867b62963192a2',
    messagingSenderId: '80742676487',
    projectId: 'focus-to-do-8e9e4',
    storageBucket: 'focus-to-do-8e9e4.appspot.com',
    iosBundleId: 'com.example.focusToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFuleDPDNLoXWKrLxQweIrJwEVLzDg4I',
    appId: '1:80742676487:ios:1afc9a05867b62963192a2',
    messagingSenderId: '80742676487',
    projectId: 'focus-to-do-8e9e4',
    storageBucket: 'focus-to-do-8e9e4.appspot.com',
    iosBundleId: 'com.example.focusToDo',
  );
}
